### ISSUE TITLE
What is the steps to run?

### ISSUE THREAD

**Issue by kailiyumit** [YeahHuang/Al_surface_defect_detection#16] opened 2020-07-02 19:27 UTC
Is there already dataset inside the folder? If not, where can I put the data? 
Which file should I run first? Can you also show the steps to train and test the data? Thanks!

**Comment by YeahHuang** [comment] 2020-12-04 13:04
Duplicate of #3 
plz refer to the answers there

**Closed as completed by YeahHuang** 2020-12-04 13:04 UTC
