### ISSUE TITLE
你好，初赛和复赛的数据能发我一份吗？eada_02@163.com

### ISSUE THREAD

**Issue by ljl02521** [YeahHuang/Al_surface_defect_detection#14] opened 2019-09-16 08:26 UTC

**Comment by YeahHuang** [comment] 2019-09-23 18:27
Duplicate of #1

**Closed as completed by YeahHuang** 2019-09-23 18:27 UTC

**Comment by ljl02521** [comment] 2019-09-23 19:21
Thanks



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "YeahHuang"<notifications@github.com&gt;; 
发送时间: 2019年9月24日(星期二) 凌晨2:27
收件人: "YeahHuang/Al_surface_defect_detection"<Al_surface_defect_detection@noreply.github.com&gt;; 
抄送: "再回首"<307583790@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [YeahHuang/Al_surface_defect_detection] 你好，初赛和复赛的数据能发我一份吗？eada_02@163.com (#14)




Closed #14.

**Comment by mechealww2** [comment] 2019-11-29 04:20
> 
> Thanks
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "YeahHuang"<notifications@github.com&gt;; 发送时间: 2019年9月24日(星期二) 凌晨2:27 收件人: "YeahHuang/Al_surface_defect_detection"<Al_surface_defect_detection@noreply.github.com&gt;; 抄送: "再回首"<307583790@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [YeahHuang/Al_surface_defect_detection] 你好，初赛和复赛的数据能发我一份吗？eada_02@163.com (#14) Closed #14. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

Can you share this data set to me？ My email is 513033200@qq.com
